# -*- coding: utf-8 -*-
"""tic_tac_toe.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hDPAIQl2aZugAHyq7cayhLKl3K4wTBT1
"""

import random

def draw_board(board):
  print(board[0], board[1], board[2], sep=' | ')
  print('---------')
  print(board[3], board[4], board[5], sep=' | ')
  print('---------')
  print(board[6],board[7], board[8],sep=' | ')

def get_player_move (board, player):
  while True:
    move = int(input('Введите число от 1 до 9: '))-1
    if 0 <= move <= 8 and board[move] == ' ':
      board[move] = player
      break
    else:
      print('Неверный ввод. Попробуйте ещё раз!')

def get_computer_move (board, player):
  while True:
    move = random.randint(0, 8)
    if board[move] == ' ':
      board[move] = player
      break
def check_win (board, player):
  for i in range(3):
    if board[i] == board[i+3] == board[i+6] == player:
      return True
  for j in range(0, 7, 3):
     if board[j] == board[j+1] == board[j+2] == player:
       return True
  if board[0] == board[4] == board[8] == player or board[2] == board[4] == board[6] == player:
    return True

def main ():
  board = [' '] * 9
  while True:
    print('Ваш ход')
    get_player_move (board, 'X')
    draw_board(board)
    if check_win (board, 'X'):
      print('Вы победили )))')
      break
    if ' ' not in board:
      print('Ничья')
      break
    print('Ход компьетера')
    get_computer_move (board, 'O')
    draw_board(board)
    if check_win (board, 'O'):
      print('Вы проиграли (((')
      break

main()
