# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cAg5dAXmVc0ue9IbmhYP_c_wR67lv4p5
"""

def Palindrom (s):
  n = 0
  for i in range (1, len(s)//2+1):
    if s[i-1] != s[-i]:
      n += 1
  if n == 0:
    return True
  else:
    return False

n = "Злата"
f = "Глазунова"
o = "Константиновна"
a = 15
def reg (surname, name, patronymic, age):
  year = str(2023 - age)
  all = (surname, name, patronymic, year, 'г.р зарегистрирован')
  return ' '.join(all)
print(reg(f, n, o, a))

def maxim(a, b, c=0):
  if a > b and a > c:
    return a
  if b > a and b > c:
    return b
  else:
    return c